stages:
  - build
  - strip

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_GENERATOR: Ninja

.build_template:
  stage: build
  artifacts:
    paths:
      - build/luxon_server.*
    expire_in: 1 week

# RelWithDebInfo static build amd64 via alpine
build:alpine:amd64:
  extends: .build_template
  image: alpine:3
  before_script:
    - apk update && apk add build-base cmake ninja git linux-headers
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXE_LINKER_FLAGS="-static"
    - cmake --build build
    - mv build/luxon_server build/luxon_server.musl-static.rel+debinfo.linux-x86_64

# RelWithDebInfo build amd64 via Debian Trixie
build:debian:amd64:
  extends: .build_template
  image: debian:trixie
  before_script:
    - apt-get update && apt-get install -y build-essential cmake ninja-build git libmbedtls-dev libspdlog-dev
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - cmake --build build
    - mv build/luxon_server build/luxon_server.glibc.rel+debinfo.linux-x86_64

# RelWithDebInfo build aarch64 via Debian Trixie
build:debian:aarch64:
  extends: .build_template
  image: debian:trixie
  before_script:
    - dpkg --add-architecture arm64
    - apt-get update && apt-get install -y build-essential crossbuild-essential-arm64 cmake ninja-build git pkg-config libmbedtls-dev:arm64 libspdlog-dev:arm64
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
    - cmake --build build
    - mv build/luxon_server build/luxon_server.glibc.rel+debinfo.linux-aarch64

# RelWithDebInfo build amd64 via llvm-mingw
build:mingw:amd64:
  extends: .build_template
  image: mstorsjo/llvm-mingw:latest
  before_script:
    - apt-get update && apt-get install -y cmake ninja-build git
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-clang -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-clang++ -DCMAKE_EXE_LINKER_FLAGS="-static"
    - cmake --build build
    - mv build/luxon_server.exe build/luxon_server.mingw.rel+debinfo.exe

# RelWithDebInfo build Nintendo 3DS via devkitpro
build:nintendo_3ds:
  extends: .build_template
  image: devkitpro/devkitarm:latest
  script:
    - source /etc/profile.d/devkit-env.sh
    - cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=${DEVKITPRO}/cmake/3DS.cmake
    - cmake --build build
    - 3dsxtool build/luxon_server.elf build/luxon_server.3dsx
    - mv build/luxon_server.elf build/luxon_server.devkitarm.rel+debinfo.elf
    - mv build/luxon_server.3dsx build/luxon_server.devkitarm.release.3dsx

# RelWithDebInfo build amd64 via Debian Trixie (FreeBSD 15.0 Sysroot)
build:freebsd:amd64:
  extends: .build_template
  image: debian:trixie
  before_script:
    - apt-get update && apt-get install -y clang lld cmake ninja-build git wget xz-utils
    - wget https://download.freebsd.org/releases/amd64/15.0-RELEASE/base.txz
    - mkdir -p freebsd-sysroot
    - tar -xf base.txz -C freebsd-sysroot
  script:
    - export SYSROOT=$PWD/freebsd-sysroot
    - >
      cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
      -DCMAKE_SYSTEM_NAME=FreeBSD
      -DCMAKE_SYSTEM_PROCESSOR=amd64
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_C_FLAGS="--target=x86_64-unknown-freebsd15.0 --sysroot=$SYSROOT"
      -DCMAKE_CXX_FLAGS="--target=x86_64-unknown-freebsd15.0 --sysroot=$SYSROOT"
      -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld --target=x86_64-unknown-freebsd15.0 --sysroot=$SYSROOT"
    - cmake --build build
    - mv build/luxon_server build/luxon_server.libc.rel+debinfo.freebsd-x86_64

# RelWithDebInfo build amd64 via MSVC
build:msvc:amd64:
  extends: .build_template
  tags:
    - saas-windows-medium-amd64
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - cmake -B build -G "Visual Studio 17 2022" -A x64 -DMBEDTLS_FATAL_WARNINGS=OFF
    - cmake --build build --config RelWithDebInfo
    - cmake -E rename build/RelWithDebInfo/luxon_server.exe build/luxon_server.msvc.release.exe
    - cmake -E rename build/RelWithDebInfo/luxon_server.pdb build/luxon_server.msvc.release.pdb

# Strips each generated rel+debinfo binary to generate release binary
strip_binaries:
  stage: strip
  image: debian:trixie
  before_script:
    - apt-get update && apt-get install -y llvm
  script:
    - rm -rf build/*.vcxproj* build/*.dir
    - |
      for file in build/*rel+debinfo*; do
        if [ -f "$file" ]; then
          release_file=$(echo "$file" | sed 's/rel+debinfo/release/')
          
          cp "$file" "$release_file"
          
          echo "Stripping $release_file..."
          llvm-strip "$release_file"
        fi
      done
  artifacts:
    paths:
      - build/luxon_server*
    expire_in: 1 week
