# Internal servers

NameServer:
  - port: 5058
  - address: 127.0.0.1:5058

MasterServer:
  - port: 5055
  - address: 127.0.0.1:5055

GameServer:
  - port: 5056
  - address: 127.0.0.1:5056


NameServer:
  - port: 27000
  - address: 127.0.0.1:27000

MasterServer:
  - port: 27001
  - address: 127.0.0.1:27001

GameServer:
  - port: 27002
  - address: 127.0.0.1:27002


# External servers (transport protocol proxies)

External:
  - type: NameServer
    address: 127.0.0.1:4533
    protocol: TCP
  - type: MasterServer
    address: 127.0.0.1:4530
    protocol: TCP
  - type: GameServer
    address: 127.0.0.1:4531
    protocol: TCP


# Misc settings

EnableIPv6: true
MaxConnections: 20
MaxGamePeers: 0 # No explicit limit
TickTimeBudget: 2000 # In microseconds, 0 to disable, more clients -> lower value; higher value -> lower latency

# Settings database
# Requires to LUXON_SERVER_ENABLE_SETTINGS_DATABASE to be enabled at build time
#SettingsDatabase: settings.sqlite3


# Web interface and API

HTTP:
  - active: true
